---
abstract: Data structure Annotation module
author: 'Jeremy Wall, all rights reserved.'
build_requires:
  Test::More: 0.7
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Annotated
no_index:
  directory:
    - inc
    - t
requires:
  Data::Path: 1.0
  perl: 5.6.0
version: 0.02
